# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data



## What is mean total number of steps taken per day?



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?


setwd("C:/Users/Sunjay007/Desktop/Reproducible Research/Assignment")
## Loading and preprocessing the data. Show any code that 
## is needed to Load the data (i.e. read.csv()) Process/transform

## the data (if necessary) into a format suitable for your analysis


if(!file.exists("data")) {
                                          dir.create("data")
}

data <- read.csv(unz("activity.zip", "activity.csv"))

## What is mean total number of steps taken per day?

## For this part of the assignment, you can ignore 
## the missing values in the dataset.


## Make a histogram of the total number of steps taken each day

hist(tapply(data$steps, data$date, sum), xlab = "Total Daily Steps", breaks = 10, 
     main = "Total of steps taken per day")

## Calculate and report the mean and median total number of steps taken per day

total.daily.steps <- as.numeric(tapply(data$steps, data$date, sum))
step.mean <- mean(total.daily.steps, na.rm = TRUE)
step.median <- median(total.daily.steps, na.rm = TRUE)

step.mean

step.median


## What is the average daily activity pattern?
## Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and 
## the average number of steps taken, averaged across all days (y-axis)


data$interval <- as.factor(as.character(data$interval))
interval.mean <- as.numeric(tapply(data$steps, data$interval, mean, na.rm = TRUE))
intervals <- data.frame(intervals = as.numeric(levels(data$interval)), interval.mean)
intervals <- intervals[order(intervals$intervals), ]

labels <- c("00:00", "05:00", "10:00", "15:00", "20:00")
labels.at <- seq(0, 2000, 500)
plot(intervals$intervals, intervals$interval.mean, type = "l", main = "Average steps 5-minute interval", 
     ylab = "Average steps", xlab = "Time of day", xaxt = "n")
axis(side = 1, at = labels.at, labels = labels)


## Which 5-minute interval, on average across all the days in the dataset, 
## contains the maximum number of steps?

intervals.sorted <- intervals[order(intervals$interval.mean, decreasing = TRUE),                              ]
head(intervals.sorted)

max.interval <- intervals.sorted$intervals[1[1]]
max.interval

### "ANSWER - The 5-minute interval with the highest average number of steps corresponds to the interval between 8:35 AM and 8:40 AM".

## Imputing missing values
## Note that there are a number of days/intervals where there are missing values (coded as NA). 
## The presence of missing days may introduce bias into some calculations or summaries of the data.

## Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

dim(data[is.na(data$steps), ])[1]

### "ANSWER - The total number of missing values in the dataset (i.e. the  
###  total number of rows with NAs) is 2304."


## Devise a strategy for filling in all of the missing values in the dataset. 
## The strategy does not need to be sophisticated. For example, 
## you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

### The ideal strategy for filling in all of the missing values in the dataset is to 
### Replace the “NA"s by the 'mean value,' we calculated for that 5-minute interval.

steps <- vector()
for (i in 1:dim(data)[1]) {
                                          if (is.na(data$steps[i])) {
                                                                                    steps <- c(steps, intervals$interval.mean[intervals$intervals == data$interval[i]])
                                          } else {
                                                                                    steps <- c(steps, data$steps[i])
                                          }
}


## Create a new dataset that is equal to the original dataset but with the missing data filled in.
missing.data.filled<- data.frame(steps = steps, date = data$date, 
                                            interval = data$interval)

## Make a histogram of the total number of steps taken each day and 
hist(tapply(missing.data.filled $steps, missing.data.filled $date, 
            sum), xlab = "Total daily steps", breaks = 20, main = "Total of steps taken per day")


## Calculate and report the mean and median total number of steps taken per day. 
total.daily.steps <- as.numeric(tapply(missing.data.filled $steps, 
                                       missing.data.filled$date, sum))
step.mean <- mean(total.daily.steps)
step.median <- median(total.daily.steps)
step.mean

step.median

### "ANSWER - The new mean of total number of steps taken per day is 10766 and 
###  The new median of total number of steps taken per day is also 10766.

## QUESTION - Do these values differ from the estimates from the first part of the assignment? 
## What is the impact of imputing missing data on the estimates of the total daily number of steps?

###  'ANSWER -The median is exactly equal to the mean. Because of the strategy chosen, 
### there is no impact of imputing missing data on the estimates of the total daily number of steps.

#### QUESTION - Are there differences in activity patterns between weekdays and weekends?

## For this part the weekdays() function may be of some help here. 
## Use the dataset with the filled-in missing values for this part.

    ## 1. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” 
       ## indicating whether a given date is a weekday or weekend day.

       ### 'ANSWER - First, classify by weekend and weekday, and
       ### repeat the previous process. Create a new factor variable with 
       ### two factor levels in the dataset - weekday and weekend - 
       ### indicating whether a given date is a weekday or weekend day.

missing.data.filled $day.type <- c("weekend", "weekday", "weekday", 
                                            "weekday", "weekday", "weekday", "weekend")[as.POSIXlt(missing.data.filled$date)$wday + 
                                                                                                                                  1]
missing.data.filled$day.type <- as.factor(missing.data.filled$day.type)

weekday <- missing.data.filled[missing.data.filled$day.type == 
                                                                                   "weekday", ]
weekend <- missing.data.filled[missing.data.filled$day.type == 
                                                                                   "weekend", ]
weekday.means <- as.numeric(tapply(weekday$steps, weekday$interval, mean))
weekend.means <- as.numeric(tapply(weekend$steps, weekend$interval, mean))

DailyInt.type <- data.frame(intervals = as.numeric(levels(data$interval)), 
                                 weekday.means, weekend.means)
DailyInt.type <- DailyInt.type[order(DailyInt.type$intervals), 
                                         ]

    ## 2. Make a panel plot containing a time series plot (i.e. type = "l") 
      ## of the 5-minute interval (x-axis) and the average number of steps taken, 
      ## averaged across all weekday days or weekend days (y-axis). 
   
      ### Plotting the two time series - weekdays and weekends - of 
      ### the 5-minute intervals and average number of steps taken.

par <- par(mfrow = c(2, 1))
plot(DailyInt.type$intervals, DailyInt.type$weekday.means, type = "l", 
     col = "red", ylab = "Average steps", xlab = "Time of day", main = "Average steps 5-minute interval at weekday", 
     xaxt = "n")
axis(side = 1, at = labels.at, labels = labels)
plot(DailyInt.type$intervals, DailyInt.type$weekend.means, type = "l", 
     col = "blue", ylab = "Average steps", xlab = "Time of day", main = "Average steps 5-minute interval at weekend", 
     xaxt = "n")
axis(side = 1, at = labels.at, labels = labels)
par(par)

 ### ANSWER - Comparing the two plots -one for the weekdays and the other for the weekends,
 ### it is clear that early mornings 8 am through 9:30 am is consistently the peak hour.
### There is a spile around 3 pm and another one around 6 pm.
### On weekend, the 6 pm spike up is of longer duration whereas
### On Weekends, the 3 pm spike up is of longer duration.
